apiVersion: apps/v1
kind: Deployment
metadata:
  name: findadoctor-backend
  namespace: findadoctor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: findadoctor-backend
  template:
    metadata:
      labels:
        app: findadoctor-backend
    spec:
      containers:
      - name: findadoctor-backend
        image: your-dockerhub-username/findadoctor-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: findadoctor-config
              key: mongo_uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: findadoctor-secrets
              key: jwt_secret