apiVersion: apps/v1
kind: Deployment
metadata:
  name: findadoctor-frontend
  namespace: findadoctor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: findadoctor-frontend
  template:
    metadata:
      labels:
        app: findadoctor-frontend
    spec:
      containers:
      - name: findadoctor-frontend
        image: your-dockerhub-username/findadoctor-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://findadoctor-backend-service:5000"