name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      DOCKER_BUILDKIT: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        eval $(minikube docker-env)

    - name: Build Backend Docker image
      run: |
        docker build -t your-dockerhub-username/findadoctor-backend:latest ./FindaDoctor-BE-main

    - name: Build Frontend Docker image
      run: |
        docker build -t your-dockerhub-username/findadoctor-frontend:latest ./FindaDoctor-FE-main

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images
      run: |
        docker push your-dockerhub-username/findadoctor-backend:latest
        docker push your-dockerhub-username/findadoctor-frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/secret.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
